### ISSUE TITLE
cannot import name 'VTIL'

### ISSUE THREAD

**Issue by maskelihileci** [vtil-project/VTIL-BinaryNinja#3]
Failed to import python plugin: community/vtilproject_VTILBinaryNinja: cannot import name 'VTIL' from 'vtilproject_VTILBinaryNinja.vtil.vtil' (C:\Users\HaXo\AppData\Roaming\Binary Ninja\repositories\community\plugins\vtilproject_VTILBinaryNinja\vtil\vtil.pyd)

**Comment by ioncodes** [comment]
Which Binary Ninja version are you on?

**Comment by can1357** [comment]
Install a separate installation of Python 3.7, pip install kaitaistruct && pip install capstone in that environment and switch to that interpreter in Binary Ninja this plugin doesn't work with the built-in Python installation that comes with Binary Ninja, because kaitai refuses to install for whatever reason.

**Comment by maskelihileci** [comment]
Version 2.0.2097 

![Screen](https://user-images.githubusercontent.com/41159853/90566113-9778ee00-e1b0-11ea-8166-84686482d2b7.PNG)

**Comment by maskelihileci** [comment]
I tried all the methods I know and couldn't find a solution


![Screen](https://user-images.githubusercontent.com/41159853/90566345-fc344880-e1b0-11ea-83c9-3cdaf47989cd.PNG)

**Comment by ioncodes** [comment]
Try Python 3.7, if that doesn't work attach your .vtil file

**Comment by ioncodes** [comment]
Also, note that this project doesn't need the `vtil` Python package. It comes with its own Kaitai structure parser. Did you install the plugin from the plugin manager or this repository?

**Comment by maskelihileci** [comment]
Oh, thank you.

Downgrade fixed the issue

I also had to set these up, maybe it'll help other friends.

python -m pip install requests
python -m pip install kaitaistruct
python -m pip install capstone

**Comment by ioncodes** [comment]
That will install automatically if you install the plugin. However, if you downgrade after installing it, the packages will be installed for the wrong version so that will help in that case
