### ISSUE TITLE
_get_instruction_info

### ISSUE THREAD

**Issue by maskelihileci** [vtil-project/VTIL-BinaryNinja#4]
Mistakes don't really end , Python 3.7 in version

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "D:\File\Ninja\Windows-BinaryNinja-personal-2.0.2097-dev\BinaryNinja-personal-2.0.2097-dev\plugins\..\python\binaryninja\architecture.py", line 515, in _get_instruction_info
    info = self.get_instruction_info(buf.raw, addr)
  File "D:\File\Ninja\Windows-BinaryNinja-personal-2.0.2097-dev\BinaryNinja-personal-2.0.2097-dev\plugins\..\python3\vtilproject_VTILBinaryNinja\vtil\vtil.py", line 215, in get_instruction_info
    next_vip, _, _, _, code = find_instruction(addr, active_vtil_file)
  File "D:\File\Ninja\Windows-BinaryNinja-personal-2.0.2097-dev\BinaryNinja-personal-2.0.2097-dev\plugins\..\python3\vtilproject_VTILBinaryNinja\vtil\utils.py", line 64, in find_instruction
    setattr(vtil, "parser_cache", {})
AttributeError: 'NoneType' object has no attribute 'parser_cache'
GetInstructionInfo invalid instruction length reported for address 0x140006378

Python 3.8 in version

Failed to import python plugin: community/vtilproject_VTILBinaryNinja: DLL load failed while importing binaryninjaui: Belirtilen modül bulunamadı.

As I mentioned in the previous topic, python 3.7 installation is happening. but the application is not working properly

python 3.8 plugin not working

Is there going to be an IDA version that doesn't require Python ?

**Comment by ioncodes** [comment]
An IDA version isn't really planned AFAIK, and even if it's probably going to be in Python as well. If it fails on importing "binaryninjaui" then your Binary Ninja installation is probably broken.

```
Failed to import python plugin: community/vtilproject_VTILBinaryNinja: DLL load failed while importing binaryninjaui: Belirtilen modül bulunamadı.
```

Remove all VTIL-BinaryNinja files, maybe also try to reinstall Binary Ninja and make sure you have Python 3.7 selected in Binary Ninja. Once you have done that, install the plugin through the marketplace again. Please also attach your VTIL file.

**Comment by ioncodes** [comment]
Seems to be an issue with Binary Ninja, @can1357 will provide more insight in this soon.

**Comment by can1357** [comment]
Install a fresh Python 3.78 x64, go into the directory of install and do:
`python -m pip install requests`
`python -m pip install kaitaistruct`
`python -m pip install capstone`

Pick the installation in BinaryNinja, move the plugin from `%appdata%/Binary Ninja/repositories/community` to `%appdata%/Binary Ninja/plugins`.

Should work fine now.
